.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "qABCs" "1" "February 11, 2019" "qABCs" "User manuals"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH "NAME"
\fBqABCs\fR \- learn alphabet application

.SH "SYNOPSIS"
\fBqabcs\fR

.SH "DESCRIPTION"
\fBqABCs\fR is Educational Software. An educational game for young children.
\fBqABCs\fR familiarizes children with the alphabet and a keyboard.
Children can play with \fBqABCs\fR to learn about the alphabet and words
associated with it.

.SH "OPTIONS"
Zero options will start \fBqABCs\fR.

.SH "AUTHOR"
The program was written by DanSoft <\&dik@inbox.ru\&>, 2019.
.PP
This manual page was written by Alexey Loginov <\&alexl@mageia.org\&>,
for the Mageia GNU/Linux system (but may be used by others).
